ProTasks/urls.py
from django.contrib import admin
from django.urls import path, include
import turmas, atividades, contas

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('turmas.urls')),
    path('atividades/', include('atividades.urls')),
    path('contas/', include('contas.urls')),
]

atividades/urls.py
from django.urls import path

from . import views

app_name = 'atividades'

urlpatterns = [
	#path('', views.atividade_index, name='index'),
	path('<int:codigo>/', views.atividade_detalhes, name="atividade"),
	path('<codigo>/cadastrar/', views.atividade_cadastrar, name='cadastrar'),
	path('<int:codigo>/editar/', views.atividade_editar, name='editar'),
	path('<int:codigo>/excluir/', views.atividade_excluir, name='excluir'),
	path('<int:codigo>/prioridade/', views.atividade_prioridade, name="prioridade"),
	path('<int:atividade>/comentar/', views.comentario_adicionar, name="comentar"),
	path('<int:codigo>/comentario/excluir', views.comentario_excluir, name="comentario_excluir"),
]

contas/urls.py
from django.urls import path

from .views import *

urlpatterns = [
	path('login/', login_view, name="login"),
    path('registrar/', register_view, name="registrar"),
    path('sair/', logout_view, name="sair"),
    path('<int:codigo>/alterar', change_view, name="alterar_cadastro"),
    path('<int:codigo>/alterar_senha', change_password_view, name="alterar_senha"),
]

turmas/urls.py
from django.urls import path

from . import views

app_name = 'turmas'

urlpatterns = [
	path('', views.turma_index, name='index'),
	path('cadastrar/', views.turma_cadastrar, name='cadastrar'),
	path('solicitar/', views.turma_solicitar, name="solicitar"),
	path('<codigo>/', views.turma_detalhes, name="turma"), 
	path('<codigo>/excluir', views.turma_excluir, name="turma_excluir"),
	path('<codigo>/editar', views.turma_editar, name="turma_editar"),

	path('<int:aem>/remover', views.remover_aluno, name="remover_aluno"),

	path('<int:codigo>/remover/solicitacao', views.remover_solicitacao, name="remover_solicitacao"),
	path('<int:codigo>/aceitar/solicitacao', views.aceitar_solicitacao, name="aceitar_solicitacao"),
]

atividades/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Atividade(models.Model):
	turma = models.ForeignKey('turmas.Turma', on_delete=models.CASCADE)
	aluno = models.ForeignKey(User, on_delete=models.CASCADE)
	disciplina = models.CharField("Nome da disciplina", max_length=200)
	atividade = models.CharField("Nome da atividade", max_length=200)
	data_cadastro = models.DateTimeField("Data de Cadastro", auto_now_add=True)
	data_modificacao = models.DateTimeField("Data de Modificação", auto_now=True)
	data_entrega = models.DateTimeField("Data de Entrega")
	valor = models.DecimalField(max_digits=4, decimal_places=2)
	observacoes = models.TextField("Observações", null=True, blank=True)
	encerrada = models.BooleanField(default=False)

	@property
	def num_comentarios(self):
		return Comentario.objects.filter(atividade = self).count()

	
	@property
	def expirou(self):
		entrega = self.data_entrega
		now = timezone.now()
		return entrega < now

class Comentario(models.Model):
	atividade = models.ForeignKey(Atividade, on_delete=models.CASCADE)
	aluno = models.ForeignKey(User, on_delete=models.CASCADE)
	comentario = models.TextField("Comentário")
	status = models.BooleanField("status", default=True)
	data_comentario = models.DateTimeField("Data de Publicação", auto_now_add=True)
	data_modificacao = models.DateTimeField("Data de Modificação", auto_now=True)

	class Meta:
		verbose_name = "Comentário"
		verbose_name_plural = "Comentários"

class Prioridade(models.Model):
	aluno = models.ForeignKey(User, verbose_name="Aluno", on_delete=models.CASCADE)
	atividade = models.ForeignKey(Atividade, on_delete=models.CASCADE)

	class Meta:
		unique_together = (("aluno", "atividade"),)

class Notificacao(models.Model):
	prioridade = models.ForeignKey(Prioridade, on_delete=models.CASCADE)
	texto = models.CharField(max_length=200)
	visualizada = models.BooleanField(default=False)

	class Meta:
		verbose_name = "Notificação"
		verbose_name_plural = "Notificações"

atividades/forms.py
from django import forms
from .models import *
#from datetimepicker.widgets import DateTimePicker

class ComentarioForm(forms.Form):
    comentario = forms.CharField(
    	widget=forms.Textarea(attrs={'class': 'summernote'})
    	)

class AtividadeForm(forms.ModelForm):
    valor = forms.DecimalField(
        min_value=0,
        max_digits=4,
        max_value=10.00,
        widget=forms.NumberInput(attrs={'placeholder':'Valor em Pontos'})
        )
    data_entrega = forms.SplitDateTimeField(
        input_date_formats = ['%d/%m/%Y'],
        input_time_formats = ['%H:%M:%S'],
        widget = forms.SplitDateTimeWidget(
            date_attrs = {'class': '', 'placeholder':'Data de Entrega'},
            time_attrs = {'class': 'clockpicker', 'placeholder':'Horário da Entrega'}),
        )
    class Meta:
        model = Atividade
        fields = ('disciplina','atividade','valor','data_entrega','observacoes')
        widgets={
            'disciplina': forms.TextInput(attrs={'placeholder':'Nome da Disciplina'}),
            'atividade': forms.TextInput(attrs={'placeholder':'Título da Avtividade'}),
            'observacoes': forms.Textarea(attrs={'class': 'summernote', 'required': 'false'})
        }

atividades/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from datetime import datetime
from turmas.models import *
from .forms  import *
from .models import *

@login_required(login_url='contas/login/')
def atividade_detalhes(request, codigo):
	atividade = get_object_or_404(Atividade, pk=codigo)
	aem = AlunoEmTurma.objects.filter(
		aluno__id=request.user.id, 
		turma__codigo=atividade.turma.codigo
		).exists()
	if aem:
		comentarios = Comentario.objects.filter(atividade=atividade).\
			order_by('data_comentario')
		if atividade.expirou and atividade.encerrada == False:
			atividade.encerrada = True
			atividade.save()
		context = {
			'atividade' : atividade,
			'comentarios': comentarios
		}
		check = Prioridade.objects.filter(aluno=request.user, atividade=atividade)
		if check:
			context['prioridade'] = True
		else:
			context['prioridade'] = False
		return render(request, 'atividades/detalhe.html', context)
	else:
		return HttpResponseRedirect('/')

@login_required(login_url='contas/login/')
def atividade_prioridade(request, codigo):
	try:
		atividade = get_object_or_404(Atividade, pk=codigo)
		if AlunoEmTurma.objects.filter(turma__codigo=atividade.turma.codigo, aluno=request.user.id).exists():
			check = Prioridade.objects.filter(aluno=request.user, atividade=atividade)
			if check:
				check.delete()
				return HttpResponseRedirect('/atividades/' + str(atividade.id) + '/')
			else:
				check = Prioridade(aluno=request.user, atividade=atividade)
				check.save()
				return HttpResponseRedirect('/atividades/' + str(atividade.id) + '/')
		else:
			return HttpResponseRedirect('/')
	except:
		return HttpResponseRedirect('/atividades/' + str(atividade.id) + '/')

@login_required(login_url='contas/login/')
def atividade_cadastrar(request, codigo):
    if AlunoEmTurma.objects.filter(turma__codigo=codigo, aluno=request.user.id).exists():
        if request.method == 'POST':
            
            if len(request.POST.get('data_entrega_1')) == 5:
                #outra gambiarra
                request.POST = request.POST.copy()
                x = request.POST.get('data_entrega_1')
                request.POST['data_entrega_1'] += ":00"
            else:
                request.POST = request.POST.copy()
                x = request.POST.get('data_entrega_1')
                request.POST['data_entrega_1'] = x[:-3] + ":00"
            
            form = AtividadeForm(request.POST)
            turma = get_object_or_404(Turma, codigo=codigo)
            if form.is_valid():
                nova_atividade = Atividade(
                    aluno = request.user,
                    turma = turma,
                    atividade = form.cleaned_data['atividade'],
                    disciplina = form.cleaned_data['disciplina'],
                    valor = form.cleaned_data['valor'],
                    data_entrega = form.cleaned_data['data_entrega'],
                    observacoes = form.cleaned_data['observacoes'],
                    )
                nova_atividade.save()
                return HttpResponseRedirect('/' + nova_atividade.turma.codigo)
            else:
                return render(request, 'atividades/form.html', {'form' : form, 'turma': turma, 'erro': 'Preencha os dados corretamente.'})
        else:
            form = AtividadeForm()
            turma = get_object_or_404(Turma, codigo=codigo)
            context = {
                'form': form,
                'turma': turma,
                'edit': False,
            }
            return render(request, 'atividades/form.html', context)
    else:
        return HttpResponseRedirect('/')

@login_required(login_url='contas/login/')
def atividade_editar(request, codigo):
    atividade = get_object_or_404(Atividade, id=codigo)
    if AlunoEmTurma.objects.filter(turma__codigo=atividade.turma.codigo, aluno=request.user.id).exists():
        if atividade.aluno == request.user:
            turma = get_object_or_404(Turma, codigo=atividade.turma.codigo)
            if request.method == 'POST':

                #Gambiarra pra truncar os segundos kkkkkk
                if len(request.POST.get('data_entrega_1')) == 5:
                    #outra gambiarra
                    request.POST = request.POST.copy()
                    x = request.POST.get('data_entrega_1')
                    request.POST['data_entrega_1'] += ":00"
                else:
                    request.POST = request.POST.copy()
                    x = request.POST.get('data_entrega_1')
                    request.POST['data_entrega_1'] = x[:-3] + ":00"
                
                form = AtividadeForm(request.POST, instance=atividade)
                if form.is_valid():
                        atividade = form.save(commit=False)
                        atividade.save()
                        return HttpResponseRedirect('/atividades/' + str(atividade.id))
                else:
                    return render(request, 'atividades/form.html', {'form' : form, 'turma': turma, 'atividade': atividade, 'edit': True, 'erro': 'Preencha os dados corretamente.'})
            else:
                form = AtividadeForm(instance=atividade)
                return render(request, 'atividades/form.html', {'form' : form, 'turma': turma, 'atividade': atividade, 'edit': True})
        else:
            return HttpResponseRedirect('/atividades/' + str(atividade.id))
    else:
        return HttpResponseRedirect('/')

@login_required(login_url='contas/login/')
def atividade_excluir(request, codigo):
	atividade = get_object_or_404(Atividade, id=codigo)
	if AlunoEmTurma.objects.filter(turma__codigo=atividade.turma.codigo, aluno=request.user.id).exists():
		turma = atividade.turma
		if atividade.aluno == request.user:
			if request.method == 'POST':
				atividade.delete()
				return HttpResponseRedirect('/' + turma.codigo)
			else:
				return HttpResponseRedirect('/atividades/' + str(atividade.id))
		else:
			return HttpResponseRedirect('/atividades/' + str(atividade.id))
	else:
		return HttpResponseRedirect('/')

@login_required(login_url='contas/login/')
def comentario_adicionar(request, atividade):
	oAtividade = get_object_or_404(Atividade, pk=atividade)
	if AlunoEmTurma.objects.filter(turma__codigo=oAtividade.turma.codigo, aluno=request.user.id).exists():
		if request.method == 'POST':
			form = ComentarioForm(request.POST)
			if form.is_valid():
				try:
					comentario = Comentario(aluno=request.user, atividade=oAtividade, \
						comentario=form.cleaned_data['comentario'])
					comentario.save()
					return HttpResponseRedirect('/atividades/' + str(atividade) + '/')
				except:
					return render(request, 'atividades/comentar.html', {'form' : form, \
						'erro':'Atividade inválida.'})
			else:
				return render(request, 'atividades/comentar.html', {'form' : form, \
					'erro':'Seu formulário ccontém erros.'})
		else:
			try:
				form = ComentarioForm()
				return render(request, 'atividades/comentar.html', {'form' : form, \
					'atividade': oAtividade})
			except:
				return render(request, 'atividades/comentar.html', {'form' : form, \
					'erro':'Atividade inválida.'})
	else:
		return HttpResponseRedirect('/')

@login_required(login_url='contas/login/')
def comentario_excluir(request, codigo):
	comentario = get_object_or_404(Comentario, id=codigo)
	if AlunoEmTurma.objects.filter(turma__codigo=comentario.atividade.turma.codigo, aluno=request.user.id).exists():
		if comentario.aluno == request.user:
			if request.method == 'POST':
				comentario.comentario = 'Comentário excluído por <strong>' + comentario.aluno.first_name + '</strong>'
				comentario.status = False
				comentario.save()
				return HttpResponseRedirect('/atividades/' + str(comentario.atividade.id))
			else:
				return HttpResponseRedirect('/atividades/' + str(comentario.atividade.id))
		elif comentario.atividade.turma.aluno == request.user:
			if request.method == 'POST':
				comentario.comentario = 'Comentário excluído por <strong>' + comentario.atividade.turma.aluno.first_name + '</strong>'
				comentario.status = False
				comentario.save()
				return HttpResponseRedirect('/atividades/' + str(comentario.atividade.id))
			else:
				return HttpResponseRedirect('/atividades/' + str(comentario.atividade.id))
		else:
			return HttpResponseRedirect('/atividades/' + str(comentario.atividade.id))	
	else:
		return HttpResponseRedirect('/')

ProTasks/templates/atividades/comentar.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% if erro %}
        <div class="alert alert-danger fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-times"></i>
            <strong>Erro!</strong> {{ erro }}
        </div>
    {% endif %}
    <!-- widget grid -->
    <section id="widget-grid" class="">

        <!-- row -->
        <div class="row">
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false"                    data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-comment"></i> </span>
                        <h2><strong>Comentar</strong></h2>
                    </header>
                    <!-- widget div-->
                    <div>
    
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
    
                        </div>
                        <!-- end widget edit box -->
    
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            <form action="{% url 'atividades:comentar' atividade.id %}" method="post" class="smart-form">
                                {% csrf_token %}
                                <header>
                                    Escrever um coment&aacute;rio
                                </header>
                                <fieldset>
                                    <section>
                                        {{ form.comentario.errors }}
                                        <label class="input" for="{{ form.comentario.id_for_label }}">
                                            {{ form.comentario }}
                                        </label>
                                    </section>
                                </fieldset>
                                <footer>
                                    <button type="submit" class="btn btn-primary">
                                        Enviar
                                    </button>
                                    <a href="{% url 'atividades:atividade' atividade.id %}" class="btn btn-default">
                                        Voltar
                                    </a>
                                </footer>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
    <div id="kkk"></div>
{% endblock content %}
{% block javascript %}
    <script src="{% static 'js/plugin/summernote/summernote.min.js' %}"></script>
    <script src="{% static 'js/plugin/summernote/lang/summernote-pt-BR.js' %}"></script>
    <script type="text/javascript">
        // DO NOT REMOVE : GLOBAL FUNCTIONS!
        
        $(document).ready(function() {
            
            pageSetUp();

            $('.summernote').summernote({
                focus: true,
                dialogsInBody: true,
                lang: 'pt-BR',
                maximumImageFileSize: 1048576, // tamanho máximo da imagem
            });
            
            $('form').submit(function(e) {
                var markupStr = $('.summernote').summernote('code');
                $('#id_comentario').html(markupStr);
            });
        });
    </script>
{% endblock javascript %}

ProTasks/templates/atividades/detalhe.html
{% extends "base.html" %}
{% load static %}
{% block breadcrumb %}
	<li>
		<h4>
			<a href="{% url 'turmas:turma' atividade.turma.codigo %}">
				<strong>
					{{ atividade.turma.nome }} - {{ atividade.turma.curso }} {{ atividade.turma.ano }}, {{ atividade.turma.turno }}	/ {{ atividade.atividade }} / Coment&aacute;rios
				</strong>
			</a>
		</h4>
	</li>
{% endblock breadcrumb %}
{% block content %}
	<!-- widget grid -->
	<section id="widget-grid" class="">

		<!-- row -->
		<div class="row">
			<!-- NEW WIDGET START -->
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false"					data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
					<header>
						<span class="widget-icon"> <i class="fa fa-pencil"></i> </span>
						<h2><strong>Detalhes da Atividade</strong></h2>
					</header>
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body no-padding">
							<div class="price-features">
								<ul class="list-unstyled text-left">
									<li>
										<h3>
											Atividade: <strong>{{ atividade.atividade }}</strong>
										</h3>
									</li>
									<li>
										<h3>
											Disciplina: <strong>{{ atividade.disciplina }}</strong>
										</h3>
									</li>
									<li>
										<h3>
											Adicionada: <strong>{{ atividade.data_cadastro }}</strong> <small>por <strong>{{ atividade.aluno.first_name }}</strong></small>
										</h3>
									</li>
									<li>
										<h3>
											Entrega: 
											{% if not atividade.expirou %}
												<strong class="text-success">{{ atividade.data_entrega }}</strong>
											{% else %}
												<strong class="text-danger">{{ atividade.data_entrega }}</strong>
											{% endif %}
										</h3>
									</li>
									<li>
										<h3>
											Valor: <strong>{{ atividade.valor }}</strong> pontos</h3>
									</li>
									<li>
										<h3>
											{% autoescape off %}
											Observações: {{ atividade.observacoes|safe }}
											{% endautoescape %}
										</h3>
									</li>
									<li>
										<h3>
											Prioridade: <span class="onoffswitch">
											<input type="checkbox" name="is_prioridade" class="onoffswitch-checkbox" id="is_prioridade" 
											{% if prioridade %}
											checked="checked"
											{% endif %}
											{% if atividade.expirou %}
											disabled="disabled" 
											{% endif %}
											>
												<label class="onoffswitch-label" for="is_prioridade"> 
													<span class="onoffswitch-inner" data-swchon-text="SIM" data-swchoff-text="N&Atilde;O"></span> 
													<span class="onoffswitch-switch"></span> 
												</label> 
										</span>
										</h3>
									</li>
								</ul>
							</div>
							{% if atividade.aluno == user %}
							<div class="widget-footer">
								<form action="{% url 'atividades:excluir' atividade.id %}" method="post" id="excluir_atividade">
									{% csrf_token %}
									<button type="submit" class="btn btn-danger pull-left">Excluir</button>
								</form>
								<a href="{% url 'atividades:editar' atividade.id %}" class="btn btn-primary">Editar</a>
							</div>
							{% endif %}
						</div>
					</div>
				</div>
			</article>
		</div>
		<!-- row -->
		<div class="row">
		
			<!-- NEW WIDGET START -->
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false"					data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
					<header>
						<span class="widget-icon"> <i class="fa fa-comments"></i> </span>
						<h2><strong>Coment&aacute;rios</strong></h2>
						{% if not atividade.expirou %}
							<div class="widget-toolbar">
								<a href="{% url 'atividades:comentar' atividade.id %}" class="btn btn-primary">
									<i class="fa fa-comment"></i>
									Comentar
								</a>
							</div>
						{% endif %}
					</header>
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body no-padding">
	
							<table id="dt_basic" class="table table-striped table-bordered table-hover" width="100%">
								<thead>			                
									<tr>
										<th data-class="expand" class="text-center">
											<i class="fa fa-fw fa-user text-muted hidden-md hidden-sm hidden-xs"></i> Aluno
										</th>
										
										<th data-class="expand" class="text-center">
											<i class="fa fa-fw fa-comment text-muted hidden-md hidden-sm hidden-xs"></i> Comentário
										</th>
									</tr>
								</thead>
								<tbody>
									{% for comentario in comentarios %}
									<tr>
										<td>
											<h5>
												{% if user.get_username == comentario.aluno.username %}
													<b>{{ comentario.aluno.first_name }}</b><br>
												{% else %}
													{{ comentario.aluno.first_name }}<br>
												{% endif %}
												<small>{{ comentario.data_comentario }}</small>
											</h5>
										</td>
										<td class="text-justify">
											<blockquote>
												<p>
													{% autoescape off %}
														{{ comentario.comentario|safe }}
													{% endautoescape %}
												</p>
											</blockquote>
											{% if comentario.status %}
												{% if comentario.aluno == user or comentario.atividade.turma.aluno == user %}
												<footer>
													<form action="{% url 'atividades:comentario_excluir' comentario.id %}" method="post" id="excluir_comentario">
														{% csrf_token %}
														<button type="submit" class="btn btn-danger btn-xs pull-left">Excluir</button>
													</form>
												</footer>
												{% endif %}
											{% endif %}
										</td>
										<!--td class="text-center">{{ comentario.data_comentario }}</td-->
									</tr>
									{% endfor %}
								</tbody>
							</table>
							{% if not atividade.expirou %}
							<div class="widget-footer">
								<a href="{% url 'atividades:comentar' atividade.id %}" class="btn btn-primary">
									<i class="fa fa-comment"></i>
									Comentar
								</a>
							</div>
							{% endif %}	
						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
				</div>
			</article>
		</div>
	</section>
{% endblock content %}

{% block javascript %}

	<!-- JARVIS WIDGETS -->
	<script src="{% static 'js/smartwidgets/jarvis.widget.min.js' %}"></script>
	
	<!-- PAGE RELATED PLUGIN(S) -->
	<script src="{% static 'js/notification/SmartNotification.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatables/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatables/dataTables.colVis.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatables/dataTables.tableTools.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatables/dataTables.bootstrap.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatable-responsive/datatables.responsive.min.js' %}"></script>

	<script>
		
		// DO NOT REMOVE : GLOBAL FUNCTIONS!
		
		$(document).ready(function() {
			
			pageSetUp();

			/* definir prioridade */

			$('#is_prioridade').click(function (e){
				window.location.replace("{% url 'atividades:prioridade' atividade.id %}");
			});

			$("#excluir_atividade").submit(function(e) {
				e.preventDefault();

				$.SmartMessageBox({
					title : "ProTasks",
					content : "Tem certeza que quer excluir esta atividade?",
					buttons : '[Sim][Não]',
					//sound:,
				}, function(ButtonPressed) {
					if (ButtonPressed === "Sim") {
						$("#excluir_atividade").unbind('submit').submit();
					}
					if (ButtonPressed === "No") {
						return false;
					}
		
				});
				e.preventDefault();
			});

			$("#excluir_comentario").submit(function(e) {
				e.preventDefault();

				$.SmartMessageBox({
					title : "ProTasks",
					content : "Tem certeza que quer excluir este comentário?",
					buttons : '[Sim][Não]',
					//sound:,
				}, function(ButtonPressed) {
					if (ButtonPressed === "Sim") {
						$("#excluir_comentario").unbind('submit').submit();
					}
					if (ButtonPressed === "No") {
						return false;
					}
		
				});
				e.preventDefault();
			});
			
			var responsiveHelper_dt_basic = undefined;

			var breakpointDefinition = {
					tablet : 1024,
					phone : 480
				};
	
			$('#dt_basic').dataTable({
				"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
					"t"+
					"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
				"autoWidth" : true,
				"ordering": false,
				"columns": [
    						null, { "width": "80%" }
    			],
		        "oLanguage": {
				    "sEmptyTable": "<strong>Ningu&eacute;m comentou ainda. Seja o primeiro!</strong>",
				    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
				    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
				    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
				    "sInfoPostFix": "",
				    "sInfoThousands": ".",
				    "sLengthMenu": "_MENU_ resultados por página",
				    "sLoadingRecords": "Carregando...",
				    "sProcessing": "Processando...",
				    "sZeroRecords": "Nenhum registro encontrado",
				    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>',
				    "oPaginate": {
				        "sNext": "Próximo",
				        "sPrevious": "Anterior",
				        "sFirst": "Primeiro",
				        "sLast": "Último"
				    },
				    "oAria": {
				        "sSortAscending": ": Ordenar colunas de forma ascendente",
				        "sSortDescending": ": Ordenar colunas de forma descendente"
				    }
				},
				"preDrawCallback" : function() {
					// Initialize the responsive datatables helper once.
					if (!responsiveHelper_dt_basic) {
						responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
					}
				},
				"rowCallback" : function(nRow) {
					responsiveHelper_dt_basic.createExpandIcon(nRow);
				},
				"drawCallback" : function(oSettings) {
					responsiveHelper_dt_basic.respond();
				}
			});
		});
	</script>
{% endblock javascript %}