ProTasks/urls.py
from django.contrib import admin
from django.urls import path, include
import turmas, atividades, contas

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('turmas.urls')),
    path('atividades/', include('atividades.urls')),
    path('contas/', include('contas.urls')),
]

contas/urls.py
from django.urls import path

from .views import *

urlpatterns = [
	path('login/', login_view, name="login"),
    path('registrar/', register_view, name="registrar"),
    path('sair/', logout_view, name="sair"),
    path('<int:codigo>/alterar', change_view, name="alterar_cadastro"),
    path('<int:codigo>/alterar_senha', change_password_view, name="alterar_senha"),
]

turmas/urls.py
from django.urls import path

from . import views

app_name = 'turmas'

urlpatterns = [
	path('', views.turma_index, name='index'),
	path('cadastrar/', views.turma_cadastrar, name='cadastrar'),
	path('solicitar/', views.turma_solicitar, name="solicitar"),
	path('<codigo>/', views.turma_detalhes, name="turma"), 
	path('<codigo>/excluir', views.turma_excluir, name="turma_excluir"),
	path('<codigo>/editar', views.turma_editar, name="turma_editar"),

	path('<int:aem>/remover', views.remover_aluno, name="remover_aluno"),

	path('<int:codigo>/remover/solicitacao', views.remover_solicitacao, name="remover_solicitacao"),
	path('<int:codigo>/aceitar/solicitacao', views.aceitar_solicitacao, name="aceitar_solicitacao"),
]

turmas/models.py
from django.db import models
from django.contrib.auth.models import User
from atividades.models import Atividade

from random import choice
# Create your models here.

class Turma(models.Model):
	aluno = models.ForeignKey(User, verbose_name="Administrador", on_delete=models.CASCADE)
	nome = models.CharField(max_length=200)
	codigo = models.CharField("Código", max_length=200, blank=True, null=True, unique=True)
	curso = models.CharField(max_length=200)
	ano = models.PositiveIntegerField("Ano/Módulo")
	turno = models.CharField(max_length=200)
	data_cadastro = models.DateTimeField("Data de Cadastro", auto_now_add=True)

	def __str__(self):
		return self.nome + " - " + self.codigo	

	@property
	def num_atividades(self):
		return Atividade.objects.filter(turma = self).count()

	def save(self, *args, **kwargs):
		if not self.codigo:
			caracteres = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
			senha = ""
			for i in range(5):
				senha += choice(caracteres)
			self.codigo = senha
			super(Turma, self).save(*args, **kwargs)
		else:
			super(Turma, self).save(*args, **kwargs)

class AlunoEmTurma(models.Model):
	aluno = models.ForeignKey(User, verbose_name="Aluno", on_delete=models.CASCADE)
	turma = models.ForeignKey(Turma, on_delete=models.CASCADE)
	data_cadastro = models.DateTimeField("Data de Cadastro", auto_now_add=True)

	class Meta:
		verbose_name_plural = "Alunos em Turmas"
		unique_together = (("aluno", "turma"),)

class Solicitacao(models.Model):
	aluno = models.ForeignKey(User, verbose_name="Aluno", on_delete=models.CASCADE)
	turma = models.ForeignKey(Turma, on_delete=models.CASCADE)
	data_cadastro = models.DateTimeField("Data de Solicitação", auto_now_add=True)

	class Meta:
		verbose_name_plural = "Solicitação"
		verbose_name_plural = "Solicitações"
		unique_together = (("aluno", "turma"),)

turmas/forms.py
from django import forms
from .models import *

class JoinTurma(forms.Form):
    codigo = forms.CharField(
    	label='C&oacute;digo', 
    	max_length=200,
    	widget=forms.TextInput(attrs={'class': 'input'})
    	)

class TurmaForm(forms.ModelForm):
    ano = forms.IntegerField(
        label='Ano/M&oacute;dulo', 
        min_value=1,
        widget=forms.NumberInput(attrs={'placeholder':'Ano/Módulo'})
        )
    class Meta:
        model = Turma
        fields = ('nome', 'curso', 'ano', 'turno')
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder':'Nome da turma'}),
            'curso': forms.TextInput(attrs={'placeholder':'Nome do Curso'}),
            'turno': forms.TextInput(attrs={'placeholder':'Turno'}),
        }
    """
	nome = forms.CharField(
    	label='Nome', 
    	max_length=200,
    	widget=forms.TextInput(attrs={'placeholder':'Nome da turma'})
    	)
	curso = forms.CharField(
    	label='Curso', 
    	max_length=200,
    	widget=forms.TextInput(attrs={'placeholder':'Nome do Curso'})
    	)
	ano = forms.IntegerField(
    	label='Ano/M&oacute;dulo', 
    	min_value=1,
    	widget=forms.NumberInput(attrs={'placeholder':'Ano/Módulo'})
    	)
	turno = forms.CharField(
    	label='Turno', 
    	max_length=200,
    	widget=forms.TextInput(attrs={'placeholder':'Turno'})
    	)
    """

turmas/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.contrib.auth.models import User
from .models import *
from .forms import *

# Create your views here.

@login_required(login_url='contas/login/')
def turma_index(request):
	ultimas_turmas = AlunoEmTurma.objects.filter(aluno=request.user).order_by('-data_cadastro')
	solicitacoes = Solicitacao.objects.filter(aluno=request.user)
	context = {
		'ultimas_turmas': ultimas_turmas,
		'solicitacoes': solicitacoes,
	}
	return render(request, 'turmas/index.html', context)

@login_required(login_url='contas/login/')
def turma_detalhes(request, codigo):
	aem = AlunoEmTurma.objects.filter(aluno__id=request.user.id, turma__codigo=codigo).exists()
	if aem:
	    turma = get_object_or_404(Turma, codigo=codigo)
	    atividades = Atividade.objects.filter(turma=turma).\
	    	order_by('encerrada','prioridade__atividade','data_entrega',).distinct()
	    alunos = AlunoEmTurma.objects.filter(turma=turma).exclude(aluno=turma.aluno)
	    solicitacoes = Solicitacao.objects.filter(turma__codigo=codigo)
	    context = {
	    	'turma' : turma,
	    	'lista_atividades': atividades,
	    	'alunos': alunos, 
	    	'solicitacoes' : solicitacoes,
	    }

	    return render(request, 'turmas/detalhe.html', context)
	else:
		return HttpResponseRedirect('/')

@login_required(login_url='contas/login/')
def turma_solicitar(request):
	if request.method == 'POST':
		form = JoinTurma(request.POST)
		if form.is_valid():
			try:
				turma = Turma.objects.get(codigo=form.cleaned_data['codigo'])
				membro = Solicitacao(aluno=request.user, turma=turma)
				check = AlunoEmTurma.objects.filter(aluno=request.user, turma=turma).exists()
				if not check:
					membro.save()
					return HttpResponseRedirect('/')
				else:
					return render(request, 'turmas/join.html', {'form' : form, 'erro':'Você já faz parte dessa turma.'})
			except:
				return render(request, 'turmas/join.html', {'form' : form, 'erro':'Código inválido.'})
		else:
			return render(request, 'turmas/join.html', {'form' : form, 'erro':'bugou'})
	else:
		form = JoinTurma()
		return render(request, 'turmas/join.html', {'form' : form})

@login_required(login_url='contas/login/')
def turma_cadastrar(request):
	if request.method == 'POST':
		form = TurmaForm(request.POST)
		if form.is_valid():
			nova_turma = Turma(
				aluno = request.user,
				nome = form.cleaned_data['nome'],
				curso = form.cleaned_data['curso'],
				ano = form.cleaned_data['ano'],
				turno = form.cleaned_data['turno'],
				)
			nova_turma.save()
			alunoEmTurma = AlunoEmTurma(turma=nova_turma, aluno=request.user)
			alunoEmTurma.save()
			return HttpResponseRedirect('/' + nova_turma.codigo)
		else:
			return render(request, 'turmas/form.html', {'form' : form, 'edit' : False})
	else:
		form = TurmaForm()
		return render(request, 'turmas/form.html', {'form' : form, 'edit' : False})

@login_required(login_url='contas/login/')
def turma_excluir(request, codigo):
	turma = get_object_or_404(Turma, codigo=codigo)
	if turma.aluno.id == request.user.id:
		if request.method == 'POST':
			turma.delete()
			return HttpResponseRedirect('/')
		else:
			return HttpResponseRedirect('/' + turma.codigo)
	else:
		return HttpResponseRedirect('/' + turma.codigo)

@login_required(login_url='contas/login/')
def turma_editar(request, codigo):
	turma = get_object_or_404(Turma, codigo=codigo)
	if turma.aluno.id == request.user.id:
		if request.method == 'POST':
			form = TurmaForm(request.POST, instance=turma)
			if form.is_valid():
				nova_turma = form.save(commit=False)
				nova_turma.aluno = request.user
				nova_turma.save()
				return HttpResponseRedirect('/' + nova_turma.codigo)
			else:
				return render(request, 'turmas/form.html', {'form' : form, 'edit' : True})
		else:
			form = TurmaForm(instance=turma)
			return render(request, 'turmas/form.html', {'form' : form, 'turma' : turma, 'edit' : True})
	else:
		return HttpResponseRedirect('/')

@login_required(login_url='contas/login/')
def remover_aluno(request, aem):
	vinculo = get_object_or_404(AlunoEmTurma, id=aem)
	if vinculo.turma.aluno.id == request.user.id or vinculo.aluno.id == request.user.id:
		if request.method == 'POST':
			vinculo.delete()
			return HttpResponseRedirect('/')
		else:
			return HttpResponseRedirect('/' + vinculo.turma.codigo)
	else:
		return HttpResponseRedirect('/' + vinculo.turma.codigo)

@login_required(login_url='contas/login/')
def remover_solicitacao(request, codigo):
	solicitacao = get_object_or_404(Solicitacao, id=codigo)
	turma = solicitacao.turma
	if (solicitacao.turma.aluno.id == request.user.id) or (solicitacao.aluno.id == request.user.id):
		solicitacao.delete()
		return HttpResponseRedirect('/' + turma.codigo)
	else:
		return HttpResponseRedirect('/' + turma.codigo)

@login_required(login_url='contas/login/')
def aceitar_solicitacao(request, codigo):
	solicitacao = get_object_or_404(Solicitacao, id=codigo)
	turma = solicitacao.turma
	if solicitacao.turma.aluno.id == request.user.id:
		aem = AlunoEmTurma(turma=solicitacao.turma, aluno=solicitacao.aluno)
		aem.save()
		solicitacao.delete()
		return HttpResponseRedirect('/' + turma.codigo)
	else:
		return HttpResponseRedirect('/' + turma.codigo)

ProTasks/templates/turmas/form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% if erro %}
        <div class="alert alert-danger fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-times"></i>
            <strong>Erro!</strong> {{ erro }}
        </div>
    {% endif %}
    <!-- widget grid -->
    <section id="widget-grid" class="">

        <!-- row -->
        <div class="row">
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false"                    data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-group"></i> </span>
                        <h2><strong>Turmas</strong></h2>
                    </header>
                    <!-- widget div-->
                    <div>
    
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
    
                        </div>
                        <!-- end widget edit box -->
    
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            {% if not edit %}
                            <form action="{% url 'turmas:cadastrar' %}" method="post" class="smart-form">
                            {% else %}
                            <form action="{% url 'turmas:turma_editar' turma.codigo %}" method="post" class="smart-form">
                            {% endif %}
                                {% csrf_token %}
                                <header>
                                    Cadastrar Turma
                                </header>
                                <fieldset>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.nome.errors }}
                                            <label class="input" for="{{ form.nome.id_for_label }}">
                                                <i class="icon-prepend fa fa-group"></i>
                                                {{ form.nome }}
                                            </label>
                                        </section>
                                    </div>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.curso.errors }}
                                            <label class="input" for="{{ form.curso.id_for_label }}">
                                                <i class="icon-prepend fa fa-university"></i>
                                                {{ form.curso }}
                                            </label>
                                        </section>
                                    </div>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.ano.errors }}
                                            <label class="input" for="{{ form.ano.id_for_label }}">
                                                <i class="icon-prepend fa fa-send"></i>
                                                {{ form.ano }}
                                            </label>
                                        </section>
                                    </div>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.turno.errors }}
                                            <label class="input" for="{{ form.turno.id_for_label }}">
                                                <i class="icon-prepend fa fa-sun-o"></i>
                                                {{ form.turno }}
                                            </label>
                                        </section>
                                    </div>
                                </fieldset>
                                <footer>
                                    <button type="submit" class="btn btn-primary">
                                        Enviar
                                    </button>
                                    <a href="{% url 'turmas:index' %}" class="btn btn-default">
                                        Voltar
                                    </a>
                                </footer>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
{% endblock content %}
{% block javascript %}
    <script type="text/javascript">
        // DO NOT REMOVE : GLOBAL FUNCTIONS!
        
        $(document).ready(function() {
            
            pageSetUp();
            $('#id_nome').focus();

        });
    </script>
{% endblock javascript %}

ProTasks/templates/turmas/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<!-- widget grid -->
	<section id="widget-grid" class="">

		<!-- row -->
		<div class="row">
		
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<!-- NEW WIDGET START -->
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false"					data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
					<header>
						<span class="widget-icon"> <i class="fa fa-group"></i> </span>
						<h2>Lista de Turmas</h2>
						<div class="widget-toolbar">
							<a class="btn btn-primary" href="{% url 'turmas:solicitar' %}">
								<i class="fa fa-check"></i> Entrar em uma Turma
							</a>
							<a class="btn btn-primary" href="{% url 'turmas:cadastrar' %}">
								<i class="fa fa-plus"></i> Cadastrar Turma
							</a>
						</div>
					</header>
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body no-padding">
	
							<table id="dt_basic" class="table table-striped table-bordered table-hover" width="100%">
								<thead>			                
									<tr>
										<th class="text-center" data-hide="phone">C&oacute;digo</th>
										<th class="text-center" data-class="expand"><i class="fa fa-fw fa-group text-muted hidden-md hidden-sm hidden-xs"></i> Turma</th>
										<th class="text-center"><i class="fa fa-fw fa-book text-muted hidden-md hidden-sm hidden-xs"></i> Atividades</th>
										<th class="text-center" data-hide="phone,tablet"><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Data de Cria&ccedil;&atilde;o</th>
										<th class="text-center" data-hide="phone,tablet"><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Participando desde</th>
									</tr>
								</thead>
								<tbody>
									{% for turma in ultimas_turmas %}
									<tr>
										<td>
											{{ turma.turma.codigo }}
										</td>
										<td>
											<a href="{% url 'turmas:turma' turma.turma.codigo %}">
												{{ turma.turma.nome }}, {{ turma.turma.curso }} {{ turma.turma.ano }} - {{ turma.turma.turno }}
											</a>
										</td>
										<td class="text-center">
											{{ turma.turma.num_atividades }} 
										</td>
										<td class="text-center">
											{{ turma.turma.data_cadastro }}
										</td>
										<td class="text-center">
											{{ turma.data_cadastro }}
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>

						</div>
						<!-- end widget content -->
	
					</div>
					<!-- end widget div -->
				</div>

				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-3" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
						<header>
							<span class="widget-icon"> <i class="fa fa-group"></i> </span>
							<h2>Solicita&ccedil;&otilde;es</h2>
						</header>
						<!-- widget div-->
						<div>
		
							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->
		
							</div>
							<!-- end widget edit box -->
		
							<!-- widget content -->
							<div class="widget-body no-padding">
		
								<table id="dt_basic3" class="table table-striped table-bordered table-hover" width="100%">
									<thead>			                
										<tr>
											<th data-class="expand" class="text-center">
												<i class="fa fa-fw fa-user text-muted hidden-md hidden-sm hidden-xs"></i> Nome
											</th>
											
											<th data-class="expand" class="text-center">
												<i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Data de Solicita&ccedil;&atilde;o
											</th>
											
											<th data-class="expand" class="text-center">
												<i class="fa fa-fw fa-warning text-muted hidden-md hidden-sm hidden-xs"></i> Ações
											</th>
										</tr>
									</thead>
									<tbody>
										{% for aem in solicitacoes %}
										<tr>
											<td>
												<h4>
													{{ aem.turma.nome }}, {{ aem.turma.curso }} {{ aem.turma.ano }} - {{ aem.turma.turno }}
												</h4>
											</td>
											<td class="text-center">{{ aem.data_cadastro }}</td>
											<td class="text-center">
												<a href="{% url 'turmas:remover_solicitacao' aem.id %}" id="remover_solicitacao" class="btn btn-danger btn-xs" rel="{{ aem.id }}">
													Remover
												</a>
											</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>

							</div>
							<!-- end widget content -->
		
						</div>
						<!-- end widget div -->
					</div>
			</article>
		</div>
	</section>
{% endblock content %}

{% block javascript %}

	<!-- JARVIS WIDGETS -->
	<script src="{% static 'js/smartwidgets/jarvis.widget.min.js' %}"></script>
	
	<!-- PAGE RELATED PLUGIN(S) -->
	<script src="{% static 'js/notification/SmartNotification.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatables/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatables/dataTables.colVis.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatables/dataTables.tableTools.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatables/dataTables.bootstrap.min.js' %}"></script>
	<script src="{% static 'js/plugin/datatable-responsive/datatables.responsive.min.js' %}"></script>

	<script>
		
		// DO NOT REMOVE : GLOBAL FUNCTIONS!
		
		$(document).ready(function() {
			
			pageSetUp();
			
			$("#remover_solicitacao").click(function(e) {
				e.preventDefault();

				$.SmartMessageBox({
					title : "ProTasks",
					content : "Tem certeza que quer excluir esta solicita&ccedil;&atilde;o?",
					buttons : '[Sim][Não]',
					//sound:,
				}, function(ButtonPressed) {
					if (ButtonPressed === "Sim") {
						window.location.replace("/"+$("#remover_solicitacao").attr("rel")+"/remover/solicitacao");
					}
					if (ButtonPressed === "Não") {
						return false;
					}
		
				});
				e.preventDefault();
			});

			var responsiveHelper_dt_basic = undefined;

			var breakpointDefinition = {
					tablet : 1024,
					phone : 480
				};
	
			$('#dt_basic').dataTable({
				"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
					"t"+
					"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
				"autoWidth" : true,
				"order": [],
		        "oLanguage": {
				    "sEmptyTable": "Nenhum registro encontrado",
				    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
				    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
				    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
				    "sInfoPostFix": "",
				    "sInfoThousands": ".",
				    "sLengthMenu": "_MENU_ resultados por página",
				    "sLoadingRecords": "Carregando...",
				    "sProcessing": "Processando...",
				    "sZeroRecords": "Nenhum registro encontrado",
				    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>',
				    "oPaginate": {
				        "sNext": "Próximo",
				        "sPrevious": "Anterior",
				        "sFirst": "Primeiro",
				        "sLast": "Último"
				    },
				    "oAria": {
				        "sSortAscending": ": Ordenar colunas de forma ascendente",
				        "sSortDescending": ": Ordenar colunas de forma descendente"
				    }
				},
				"preDrawCallback" : function() {
					// Initialize the responsive datatables helper once.
					if (!responsiveHelper_dt_basic) {
						responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
					}
				},
				"rowCallback" : function(nRow) {
					responsiveHelper_dt_basic.createExpandIcon(nRow);
				},
				"drawCallback" : function(oSettings) {
					responsiveHelper_dt_basic.respond();
				}
			});
			$('#dt_basic3').dataTable({
				"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
					"t"+
					"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
				"autoWidth" : true,
				"order": [],
		        "oLanguage": {
				    "sEmptyTable": "Nenhum registro encontrado",
				    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
				    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
				    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
				    "sInfoPostFix": "",
				    "sInfoThousands": ".",
				    "sLengthMenu": "_MENU_ resultados por página",
				    "sLoadingRecords": "Carregando...",
				    "sProcessing": "Processando...",
				    "sZeroRecords": "Nenhum registro encontrado",
				    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>',
				    "oPaginate": {
				        "sNext": "Próximo",
				        "sPrevious": "Anterior",
				        "sFirst": "Primeiro",
				        "sLast": "Último"
				    },
				    "oAria": {
				        "sSortAscending": ": Ordenar colunas de forma ascendente",
				        "sSortDescending": ": Ordenar colunas de forma descendente"
				    }
				},
				"preDrawCallback" : function() {
					// Initialize the responsive datatables helper once.
					if (!responsiveHelper_dt_basic) {
						responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
					}
				},
			});
		});
	</script>
{% endblock javascript %}

ProTasks/templates/turmas/join.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	{% if erro %}
		<div class="alert alert-danger fade in">
			<button class="close" data-dismiss="alert">
				×
			</button>
			<i class="fa-fw fa fa-times"></i>
			<strong>Erro!</strong> {{ erro }}
		</div>
	{% endif %}
	<!-- widget grid -->
	<section id="widget-grid" class="">

		<!-- row -->
		<div class="row">
			<!-- NEW WIDGET START -->
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false"					data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
					<header>
						<span class="widget-icon"> <i class="fa fa-group"></i> </span>
						<h2><strong>Turmas</strong></h2>
					</header>
					<!-- widget div-->
					<div>
	
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
	
						</div>
						<!-- end widget edit box -->
	
						<!-- widget content -->
						<div class="widget-body no-padding">
							<form action="{% url 'turmas:solicitar' %}" method="post" class="smart-form">
								{% csrf_token %}
								{{ form.non_field_errors }}
								<header>
									Entrar em uma Turma
								</header>
								<fieldset>
									<section>
										{{ form.codigo.errors }}
										<label class="label">C&oacute;digo da Turma</label>
										<label class="input" for="{{ form.codigo.id_for_label }}">
											{{ form.codigo }}
										</label>
									</section>
								</fieldset>
								<footer>
									<button type="submit" class="btn btn-primary">
										Enviar
									</button>
									<a href="/" class="btn btn-default">
										Voltar
									</a>
								</footer>
							</form>
						</div>
					</div>
				</div>
			</article>
		</div>
	</section>

{% endblock content %}