ProTasks/urls.py
from django.contrib import admin
from django.urls import path, include
import turmas, atividades, contas

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('turmas.urls')),
    path('atividades/', include('atividades.urls')),
    path('contas/', include('contas.urls')),
]

contas/urls.py
from django.urls import path

from .views import *

urlpatterns = [
	path('login/', login_view, name="login"),
    path('registrar/', register_view, name="registrar"),
    path('sair/', logout_view, name="sair"),
    path('<int:codigo>/alterar', change_view, name="alterar_cadastro"),
    path('<int:codigo>/alterar_senha', change_password_view, name="alterar_senha"),
]

turmas/urls.py
from django.urls import path

from . import views

app_name = 'turmas'

urlpatterns = [
	path('', views.turma_index, name='index'),
	path('cadastrar/', views.turma_cadastrar, name='cadastrar'),
	path('solicitar/', views.turma_solicitar, name="solicitar"),
	path('<codigo>/', views.turma_detalhes, name="turma"), 
	path('<codigo>/excluir', views.turma_excluir, name="turma_excluir"),
	path('<codigo>/editar', views.turma_editar, name="turma_editar"),

	path('<int:aem>/remover', views.remover_aluno, name="remover_aluno"),

	path('<int:codigo>/remover/solicitacao', views.remover_solicitacao, name="remover_solicitacao"),
	path('<int:codigo>/aceitar/solicitacao', views.aceitar_solicitacao, name="aceitar_solicitacao"),
]

contas/models.py
from django.db import models

# Create your models here.

contas/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model

)

User = get_user_model()


class UserLoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

	def clean(self, *args, **kwargs):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')

		if username and password:
			user = authenticate(username=username, password=password)
			if not user:
				print('Forms.py: Usuario não existe')
				raise forms.ValidationError('Usuário ou senha inválidos.')
			if not user.is_active:
				print('Forms.py: Este usuário não está ativo')
				raise forms.ValidationError('Este usuário não está ativo.')
			return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
	username = forms.CharField()
	first_name = forms.CharField()
	email = forms.EmailField(label='Email address')
	password = forms.CharField(widget=forms.PasswordInput)
	confirm_password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = {
			'username',
			'first_name',
			'email',
			'password',
			'confirm_password',
		}

	def clean(self, *args, **kwargs):
		email = self.cleaned_data.get('email')
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		
		confirm_password = self.cleaned_data.get('confirm_password')
		if password != confirm_password:
			raise forms.ValidationError("Senhas não conferem")
		
		email_qs = User.objects.filter(email=email)
		if email_qs.exists():
			raise forms.ValidationError(
				"Este email já está registrado para outro usuário.")
		
		if User.objects.filter(username=username).exists():
			raise forms.ValidationError(
				"Este nome de usuário já está registrado.")
		
		return super(UserRegisterForm, self).clean(*args, **kwargs)

class UserChangeForm(forms.ModelForm):
	email = forms.EmailField(label='Email address')

	class Meta:
		model = User
		fields = [
			'username',
			'email',
			'first_name',
		]

class UserChangePassWordForm(forms.ModelForm):
	old_password = forms.CharField(
		widget = forms.PasswordInput(
			attrs = {"placeholder" : "Senha antiga"}
			)
		)
	password = forms.CharField(
		widget=forms.PasswordInput(
			attrs={"placeholder" : "Nova senha"}
			)
		)
	confirm_password = forms.CharField(
		widget=forms.PasswordInput(
			attrs={"placeholder" : "Confirme a nova senha"}
			)
		)

	class Meta:
		model = User
		fields = [
			'old_password',
			'password',
			'confirm_password',
		]

	def clean(self, *args, **kwargs):
		password = self.cleaned_data.get('password')
		confirm_password = self.cleaned_data.get('password')
		
		confirm_password = self.cleaned_data.get('confirm_password')
		if password != confirm_password:
			raise forms.ValidationError("Senhas não conferem")

		return super(UserChangePassWordForm, self).clean(*args, **kwargs)

turmas/forms.py
from django import forms
from .models import *

class JoinTurma(forms.Form):
    codigo = forms.CharField(
    	label='C&oacute;digo', 
    	max_length=200,
    	widget=forms.TextInput(attrs={'class': 'input'})
    	)

class TurmaForm(forms.ModelForm):
    ano = forms.IntegerField(
        label='Ano/M&oacute;dulo', 
        min_value=1,
        widget=forms.NumberInput(attrs={'placeholder':'Ano/Módulo'})
        )
    class Meta:
        model = Turma
        fields = ('nome', 'curso', 'ano', 'turno')
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder':'Nome da turma'}),
            'curso': forms.TextInput(attrs={'placeholder':'Nome do Curso'}),
            'turno': forms.TextInput(attrs={'placeholder':'Turno'}),
        }
    """
	nome = forms.CharField(
    	label='Nome', 
    	max_length=200,
    	widget=forms.TextInput(attrs={'placeholder':'Nome da turma'})
    	)
	curso = forms.CharField(
    	label='Curso', 
    	max_length=200,
    	widget=forms.TextInput(attrs={'placeholder':'Nome do Curso'})
    	)
	ano = forms.IntegerField(
    	label='Ano/M&oacute;dulo', 
    	min_value=1,
    	widget=forms.NumberInput(attrs={'placeholder':'Ano/Módulo'})
    	)
	turno = forms.CharField(
    	label='Turno', 
    	max_length=200,
    	widget=forms.TextInput(attrs={'placeholder':'Turno'})
    	)
    """

contas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout,
	update_session_auth_hash
)

from .forms import *

User = get_user_model()

def login_view(request):
	if not request.user.is_authenticated:
		next = request.GET.get('next')
		form = UserLoginForm(request.POST or None)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			login(request, user)
			if next:
				return HttpResponseRedirect(next)
			return HttpResponseRedirect('/')

		context = {
			'form': form,
		}
		return render(request, "contas/login.html", context)
	return HttpResponseRedirect('/')


def register_view(request):
	if not request.user.is_authenticated:
		next = request.GET.get('next')
		form = UserRegisterForm(request.POST or None)
		if form.is_valid():
			user = form.save(commit=False)
			password = form.cleaned_data.get('password')
			user.set_password(password)
			user.save()
			new_user = authenticate(username=user.username, password=password)
			login(request, new_user)
			if next:
				return HttpResponseRedirect(next)
			return HttpResponseRedirect('/')

		context = {
			'form': form,
		}
		return render(request, "contas/registrar.html", context)
	else:
		return HttpResponseRedirect('/')


def logout_view(request):
	logout(request)
	return HttpResponseRedirect('/')

@login_required(login_url='contas/login/')
def change_view(request, codigo):
	usuario = get_object_or_404(User, id=codigo)
	form = UserChangeForm(request.POST or None, instance=usuario)
	if form.is_valid():

		old_user = get_object_or_404(User, id=codigo)
		new_email = form.cleaned_data['email']
		if not User.objects.filter(email=new_email).exclude(email=old_user.email).exists():
			user = form.save(commit=False)
			user.save()
			return HttpResponseRedirect('/')
		else:
			messages.error(request, "Este email já está registrado para outro usuário.")
			context = {
				'form': form,
			}
			return render(request, "contas/alterar_cadastro.html", context)
	context = {
		'form': form,
	}
	return render(request, "contas/alterar_cadastro.html", context)

@login_required(login_url='contas/login/')
def change_password_view(request, codigo):
	usuario = get_object_or_404(User, id=codigo)
	form = UserChangePassWordForm(request.POST or None)
	if form.is_valid():
		old_password = form.cleaned_data['old_password']
		new_password = form.cleaned_data['password']
		if usuario.check_password(old_password):
			usuario.set_password(new_password)
			usuario.save()
			update_session_auth_hash(request, usuario)
			return HttpResponseRedirect('/')
		else:
			messages.error(request, "Senha incorreta.")
			context = {
				'form': form,
			}
			return render(request, "contas/alterar_senha.html", context)
	context = {
		'form': form,
	}
	return render(request, "contas/alterar_senha.html", context)

ProTasks/templates/contas/alterar_cadastro.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% if messages %}
        {% for error in messages %}
            <div class="alert alert-danger fade in">
                <button class="close" data-dismiss="alert">
                    ×
                </button>
                <i class="fa-fw fa fa-times"></i>
                <strong>Erro!</strong> {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    <!-- widget grid -->
    <section id="widget-grid" class="">

        <!-- row -->
        <div class="row">
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false"                    data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-group"></i> </span>
                        <h2><strong>Usu&aacute;rio</strong></h2>
                    </header>
                    <!-- widget div-->
                    <div>
    
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
    
                        </div>
                        <!-- end widget edit box -->
    
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            <form action="{% url 'alterar_cadastro' user.id %}" method="post" class="smart-form">
                                {% csrf_token %}
                                <header>
                                    Alterar dados do Cadastro
                                </header>
                                <fieldset>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.first_name.errors }}
                                            <label class="input" for="{{ form.first_name.id_for_label }}">
                                                <i class="icon-prepend fa fa-user"></i>
                                                {{ form.first_name }}
                                            </label>
                                        </section>
                                    </div>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.username.errors }}
                                            <label class="input" for="{{ form.username.id_for_label }}">
                                                <i class="icon-prepend fa fa-user"></i>
                                                {{ form.username }}
                                            </label>
                                        </section>
                                    </div>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.email.errors }}
                                            <label class="input" for="{{ form.email.id_for_label }}">
                                                <i class="icon-prepend fa fa-envelope"></i>
                                                {{ form.email }}
                                            </label>
                                        </section>
                                    </div>
                                </fieldset>
                                <footer>
                                    <button type="submit" class="btn btn-primary">
                                        Enviar
                                    </button>
                                    <a href="{% url 'turmas:index' %}" class="btn btn-default">
                                        Voltar
                                    </a>
                                </footer>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
{% endblock content %}
{% block javascript %}
    <script type="text/javascript">
        // DO NOT REMOVE : GLOBAL FUNCTIONS!
        
        $(document).ready(function() {
            
            pageSetUp();
            $('#id_nome').focus();

        });
    </script>
{% endblock javascript %}

ProTasks/templates/contas/alterar_senha.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% if messages %}
        {% for error in messages %}
            <div class="alert alert-danger fade in">
                <button class="close" data-dismiss="alert">
                    ×
                </button>
                <i class="fa-fw fa fa-times"></i>
                <strong>Erro!</strong> {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger fade in">
                <button class="close" data-dismiss="alert">
                    ×
                </button>
                <i class="fa-fw fa fa-times"></i>
                <strong>Erro!</strong> {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    <!-- widget grid -->
    <section id="widget-grid" class="">

        <!-- row -->
        <div class="row">
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false"data-widget-togglebutton="false"                    data-widget-deletebutton="false" data-widget-sortable="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-group"></i> </span>
                        <h2><strong>Usu&aacute;rio</strong></h2>
                    </header>
                    <!-- widget div-->
                    <div>
    
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
    
                        </div>
                        <!-- end widget edit box -->
    
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            <form action="{% url 'alterar_senha' user.id %}" method="post" class="smart-form">
                                {% csrf_token %}
                                <header>
                                    Alterar Senha
                                </header>
                                <fieldset>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.old_password.errors }}
                                            <label class="input" for="{{ form.old_password.id_for_label }}">
                                                <i class="icon-prepend fa fa-lock"></i>
                                                {{ form.old_password }}
                                            </label>
                                        </section>
                                    </div>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.password.errors }}
                                            <label class="input" for="{{ form.password.id_for_label }}">
                                                <i class="icon-prepend fa fa-lock"></i>
                                                {{ form.password }}
                                            </label>
                                        </section>
                                    </div>
                                    <div class="row">
                                        <section class="col col-6">
                                            {{ form.confirm_password.errors }}
                                            <label class="input" for="{{ form.confirm_password.id_for_label }}">
                                                <i class="icon-prepend fa fa-lock"></i>
                                                {{ form.confirm_password }}
                                            </label>
                                        </section>
                                    </div>
                                </fieldset>
                                <footer>
                                    <button type="submit" class="btn btn-primary">
                                        Enviar
                                    </button>
                                    <a href="{% url 'turmas:index' %}" class="btn btn-default">
                                        Voltar
                                    </a>
                                </footer>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
{% endblock content %}
{% block javascript %}
    <script type="text/javascript">
        // DO NOT REMOVE : GLOBAL FUNCTIONS!
        
        $(document).ready(function() {
            
            pageSetUp();
            $('#id_old_password').focus();

        });
    </script>
{% endblock javascript %}

ProTasks/templates/contas/forgotpassword.html
<!DOCTYPE html>
<html lang="en-us" id="extr-page">
	<head>
		<meta charset="utf-8">
		<title> SmartAdmin</title>
		<meta name="description" content="">
		<meta name="author" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		
		<!-- #CSS Links -->
		<!-- Basic Styles -->
		<link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="css/font-awesome.min.css">

		<!-- SmartAdmin Styles : Caution! DO NOT change the order -->
		<link rel="stylesheet" type="text/css" media="screen" href="css/smartadmin-production.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="css/smartadmin-skins.min.css">

		<!-- SmartAdmin RTL Support -->
		<link rel="stylesheet" type="text/css" media="screen" href="css/smartadmin-rtl.min.css"> 

		<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="css/your_style.css"> -->

		<!-- #FAVICONS -->
		<link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon">
		<link rel="icon" href="img/favicon/favicon.ico" type="image/x-icon">

		<!-- #GOOGLE FONT -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

		<!-- #APP SCREEN / ICONS -->
		<!-- Specifying a Webpage Icon for Web Clip 
			 Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
		<link rel="apple-touch-icon" href="img/splash/sptouch-icon-iphone.png">
		<link rel="apple-touch-icon" sizes="76x76" href="img/splash/touch-icon-ipad.png">
		<link rel="apple-touch-icon" sizes="120x120" href="img/splash/touch-icon-iphone-retina.png">
		<link rel="apple-touch-icon" sizes="152x152" href="img/splash/touch-icon-ipad-retina.png">
		
		<!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		
		<!-- Startup image for web apps -->
		<link rel="apple-touch-startup-image" href="img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
		<link rel="apple-touch-startup-image" href="img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
		<link rel="apple-touch-startup-image" href="img/splash/iphone.png" media="screen and (max-device-width: 320px)">

	</head>
	
	<body class="animated fadeInDown">
		<!-- possible classes: minified, no-right-panel, fixed-ribbon, fixed-header, fixed-width-->
		<header id="header">
			<!--<span id="logo"></span>-->

			<div id="logo-group">
				<span id="logo"> <img src="img/logo.png" alt="SmartAdmin"> </span>

				<!-- END AJAX-DROPDOWN -->
			</div>

			<span id="extr-page-header-space"> <span class="hidden-mobile hidden-xs">Need an account?</span> <a href="register.html" class="btn btn-danger">Create account</a> </span>

		</header>

		<div id="main" role="main">

			<!-- MAIN CONTENT -->
			<div id="content" class="container">

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
						<h1 class="txt-color-red login-header-big">SmartAdmin</h1>
						<div class="hero">

							<div class="pull-left login-desc-box-l">
								<h4 class="paragraph-header">It's Okay to be Smart. Experience the simplicity of SmartAdmin, everywhere you go!</h4>
								<div class="login-app-icons">
									<a href="javascript:void(0);" class="btn btn-danger btn-sm">Frontend Template</a>
									<a href="javascript:void(0);" class="btn btn-danger btn-sm">Find out more</a>
								</div>
							</div>
							
							<img src="img/demo/iphoneview.png" class="pull-right display-image" alt="" style="width:210px">

						</div>

						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
								<h5 class="about-heading">About SmartAdmin - Are you up to date?</h5>
								<p>
									Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
								</p>
							</div>
							<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
								<h5 class="about-heading">Not just your average template!</h5>
								<p>
									Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
								</p>
							</div>
						</div>

					</div>
					<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
						<div class="well no-padding">
							<form action="login.html" id="login-form" class="smart-form client-form">
								<header>
									Forgot Password
								</header>

								<fieldset>
									
									<section>
										<label class="label">Enter your email address</label>
										<label class="input"> <i class="icon-append fa fa-envelope"></i>
											<input type="email" name="email">
											<b class="tooltip tooltip-top-right"><i class="fa fa-envelope txt-color-teal"></i> Please enter email address for password reset</b></label>
									</section>
									<section>
										<span class="timeline-seperator text-center text-primary"> <span class="font-sm">OR</span> </span>
									</section>
									<section>
										<label class="label">Your Username</label>
										<label class="input"> <i class="icon-append fa fa-user"></i>
											<input type="text" name="username">
											<b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Enter your username</b> </label>
										<div class="note">
											<a href="login.html">I remembered my password!</a>
										</div>
									</section>

								</fieldset>
								<footer>
									<button type="submit" class="btn btn-primary">
										<i class="fa fa-refresh"></i> Reset Password
									</button>
								</footer>
							</form>

						</div>
						
						<h5 class="text-center"> - Or sign in using -</h5>
															
										<ul class="list-inline text-center">
											<li>
												<a href="javascript:void(0);" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
											</li>
											<li>
												<a href="javascript:void(0);" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
											</li>
											<li>
												<a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
											</li>
										</ul>
						
					</div>
				</div>
			</div>

		</div>

		<!--================================================== -->	

	    <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
	    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script> if (!window.jQuery) { document.write('<script src="js/libs/jquery-3.2.1.min.js"><\/script>');} </script>

	    <!--<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
		<script> if (!window.jQuery.ui) { document.write('<script src="js/libs/jquery-ui.min.js"><\/script>');} </script>-->

		<!-- IMPORTANT: APP CONFIG -->
		<script src="js/app.config.js"></script>

		<!-- JS TOUCH : include this plugin for mobile drag / drop touch events 		
		<script src="js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

		<!-- BOOTSTRAP JS -->		
		<script src="js/bootstrap/bootstrap.min.js"></script>
		
		<!--[if IE 8]>
			
			<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
			
		<![endif]-->

		<!-- MAIN APP JS FILE -->
		<script src="js/app.min.js"></script>


	</body>
</html>

ProTasks/templates/contas/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us" id="extr-page">
	<head>
		<meta charset="utf-8">
		<title> ProTasks</title>
		<meta name="description" content="">
		<meta name="author" content="Marcos Wenyo">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		
		<!-- #CSS Links -->
		<!-- Basic Styles -->
		<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/font-awesome.min.css' %}">

		<!-- SmartAdmin Styles : Caution! DO NOT change the order -->
		<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smartadmin-production.min.css' %}">
		<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smartadmin-skins.min.css' %}">

		<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="css/your_style.css"> -->

		<!-- #FAVICONS -->
		<link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">
		<link rel="icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">

		
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">

	</head>
	
	<body class="animated fadeInDown">

		<header id="header">

			<div id="logo-group">
				<span id="logo"> <img src="{% static 'img/logo.png' %}" alt="SmartAdmin"> </span>
			</div>
		</header>

		<div id="main" role="main">

			<!-- MAIN CONTENT -->
			<div id="content" class="container">
				{% if form.non_field_errors %}
					{% for error in form.non_field_errors %}
						<div class="alert alert-danger fade in">
							<button class="close" data-dismiss="alert">
								×
							</button>
							<i class="fa-fw fa fa-times"></i>
							<strong>Erro!</strong> {{ error }}
						</div>
					{% endfor %}
				{% endif %}
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 hidden-xs hidden-sm"></div>
					<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
						<div class="well no-padding">
							<form action="{% url 'login' %}" id="login-form" class="smart-form client-form" method="post">
								{% csrf_token %}
								<header>
									ProTasks
								</header>

								<fieldset>
									
									<section>
										<label class="label">Usu&aacute;rio</label>
										<label class="input"> <i class="icon-append fa fa-user"></i>
											{{ form.username }}
											<b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Entre com seu nome de usu&aacute;rio</b></label>
									</section>

									<section>
										<label class="label">Senha</label>
										<label class="input"> <i class="icon-append fa fa-lock"></i>
											{{ form.password }}
											<b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Entre com sua senha</b> </label>
										<div class="note">
											<a href="#">Esqueceu a senha?</a>
										</div>
									</section>
								</fieldset>
								<footer>
									<button type="submit" class="btn btn-primary">
										Entrar
									</button>
									<a href="{% url 'registrar' %}" class="btn btn-danger pull-left">Crie uma conta</a> </span>
								</footer>
							</form>

						</div>
					</div>
				</div>
			</div>

		</div>

		<!--================================================== -->	

	    <script src="{% static 'js/libs/jquery-3.2.1.min.js' %}"></script>

	    <!--<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
		<script> if (!window.jQuery.ui) { document.write('<script src="js/libs/jquery-ui.min.js"><\/script>');} </script>-->

		<!-- IMPORTANT: APP CONFIG -->
		<script src="{% static 'js/app.config.js' %}"></script>

		<!-- JS TOUCH : include this plugin for mobile drag / drop touch events 		
		<script src="js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

		<!-- BOOTSTRAP JS -->		
		<script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
		
		<!--[if IE 8]>
			
			<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
			
		<![endif]-->

		<!-- MAIN APP JS FILE -->
		<script src="{% static 'js/app.min.js' %}"></script>
	</body>
</html>